name: Scala CI

on:
  push:
    paths:
      - 'server/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Scalafmt Action
        # You may pin to the exact commit or the version.
        # uses: openlawteam/scalafmt-ci@2688abc88101f179a5a540a59db9da98908e8115
        uses: openlawteam/scalafmt-ci@v2.0.2
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'

    - name: Coursier cache
      uses: coursier/cache-action@v6

    - name: Build and Test
      run: sbt -v +test

    - name: Cleanup before cache
      shell: bash
      run: |
        rm -rf "$HOME/.ivy2/local" || true
        find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
        find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
        find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
        find $HOME/.sbt                              -name "*.lock"               -delete || true